server:
  port: 4003
  servlet:
    context-path: /authz
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

spring:
  application:
    name: authz-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5003/authz_db}
    username: ${DB_USERNAME:authz_user}
    password: ${DB_PASSWORD:authz_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 3
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 4
          max-wait: -1ms

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      retries: 3
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        auto.register.schemas: true
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
        compression.type: snappy
        linger.ms: 10
        batch.size: 32768
    consumer:
      group-id: authz-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        max.poll.records: 10
        max.poll.interval.ms: 300000
        isolation.level: read_committed

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=5m
    cache-names:
      - permissions
      - roles
      - policies
      - user-permissions
      - tenant-permissions

# Authorization Service Configuration
authz:
  cache:
    user-permissions:
      ttl: 300 # 5 minutes
      max-size: 10000
    roles:
      ttl: 600 # 10 minutes
      max-size: 5000
    policies:
      ttl: 600 # 10 minutes
      max-size: 5000
    resources:
      ttl: 300 # 5 minutes
      max-size: 10000
    cross-tenant-access:
      ttl: 600 # 10 minutes
      max-size: 5000
    resource-types:
      ttl: 3600 # 1 hour
      max-size: 100
    permission-actions:
      ttl: 3600 # 1 hour
      max-size: 100

  performance:
    batch-size: 100
    max-hierarchy-depth: 10
    max-permissions-per-role: 100
    max-policies-per-resource: 50

  security:
    tenant-isolation:
      strict-mode: true
      audit-all-cross-tenant: true
      validate-resource-ownership: true

  cleanup:
    expired-policies:
      enabled: true
      cron: "0 0 2 * * *" # Daily at 2 AM
    expired-permissions:
      enabled: true
      cron: "0 0 3 * * *" # Daily at 3 AM

  evaluation:
    max-policy-depth: ${MAX_POLICY_DEPTH:10}
    enable-audit-logging: ${ENABLE_AUDIT_LOGGING:true}

  default-roles:
    - SUPER_ADMIN
    - TENANT_ADMIN
    - USER
    - VIEWER

  system-permissions:
    - SYSTEM_MANAGE
    - TENANT_MANAGE
    - USER_MANAGE
    - ROLE_MANAGE
    - PERMISSION_MANAGE

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      tenant-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
      auth-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

  retry:
    instances:
      tenant-service:
        max-attempts: 3
        wait-duration: 1000
        retry-exceptions:
          - java.net.ConnectException
          - java.io.IOException

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,cache
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      service: authz-service
  prometheus:
    metrics:
      export:
        enabled: true

# Add SpringDoc configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: false
    filter: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false


# Logging
logging:
  level:
    com.nnipa.authz: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/authorization-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30